name: pre-merge-checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:


  check_doc_strings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run Interrogate locally
        run: |
          if [ $(interrogate -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi





  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable




  run_tests:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - name: run tests
        run: |
          pip install -e .[dev]
          pytest -x

